spring.application.name=client-service
server.port=${SERVER_PORT:8081}

spring.mongodb.uri=mongodb://${MONGO_USER:clientuser}:${MONGO_PASSWORD:clientpass}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:client_db}?authSource=admin
